apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: rhel7-fluentd
    name: rhel7-fluentd-bc
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: rhel7-fluentd:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/arctiqteam/rhel7-fluentd
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/rhscl/ruby-23-rhel7
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: rhel7-fluentd
    name: rhel7-fluentd
  spec:
    replicas: 1
    selector:
      app: rhel7-fluentd
      deploymentconfig: rhel7-fluentd
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: rhel7-fluentd
          deploymentconfig: rhel7-fluentd
      spec:
        containers:
        - image: rhel7-fluentd:latest
          imagePullPolicy: Always
          name: rhel7-fluentd
          ports:
          - containerPort: 24224
            protocol: TCP
          - containerPort: 5140
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: fluentd-configs
          name: fluentd-configs
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rhel7-fluentd
        from:
          kind: ImageStreamTag
          name: rhel7-fluentd:latest
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 2
    labels:
      app: rhel7-fluentd
    name: rhel
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhel7/rhel
      from:
        kind: DockerImage
        name: rhel:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: rhel7-fluentd
    name: rhel7-fluentd
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: rhel7-fluentd:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  data:
    fluent.conf: "<source>\n  @type secure_forward\n  self_hostname \"#{ENV['HOSTNAME']}\"\n
      \ bind 0.0.0.0\n  port  24224\n  shared_key supersecretkey\n  secure no\n</source>\n<match
      *.**>\n  @type copy\n  <store>\n    @type elasticsearch\n    logstash_format
      true\n    host  elk.elk.svc.cluster.local\n    port 9200 \n    index_name fluentd
      \n    type_name fluentd \n  </store>\n</match>\n"
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: fluentd-configs
kind: List
metadata: {}