apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: rhel7-fluentd
    name: rhel7-fluentd
  spec:
    replicas: 1
    selector:
      app: rhel7-fluentd
      deploymentconfig: rhel7-fluentd
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: rhel7-fluentd
          deploymentconfig: rhel7-fluentd
      spec:
        containers:
        - image: arctiqteam/rhel7-fluentd:latest
          imagePullPolicy: Always
          name: rhel7-fluentd
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 24224
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /fluentd/etc
            name: volume-iw73z
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: rhel7-fluentd-configs
          name: volume-iw73z
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  data:
    fluent.conf: "<source>\n  @type secure_forward\n  self_hostname \"#{ENV['HOSTNAME']}\"\n
      \ bind 0.0.0.0\n  port  24224\n  shared_key supersecretkey\n  secure no\n</source>\n<match
      *.**>\n  @type copy\n  <store>\n    @type elasticsearch\n    logstash_format
      true\n    host  elk.elk.svc.cluster.local\n    port 9200 \n    index_name fluentd
      \n    type_name fluentd \n  </store>\n</match>\n"
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: rhel7-fluentd-configs
kind: List
metadata: {}
